In [3]:
import numpy as np

In [28]:
# array

a = np.array([53,67,3,2,667,3,5,'sti','python','shub'])

In [5]:
a

array(['53', '67', '3', '2', '667', '3', '5', 'sti', 'python', 'shub'],
      dtype='<U21')

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('<U21')

In [9]:
b = np.array([532,534,56345,42,549,872])

In [10]:
b

array([  532,   534, 56345,    42,   549,   872])

In [11]:
type(b)

numpy.ndarray

In [12]:
b.dtype

dtype('int64')

In [13]:
c = np.array([43,354,34],dtype='int32')

In [14]:
c

array([ 43, 354,  34], dtype=int32)

In [27]:
c.astype('float16') # 16,32,64,128..

array([ 43., 354.,  34.], dtype=float16)

In [32]:
# 0d
_ = np.array(3)

In [40]:
_

array(3)

In [35]:
_.ndim

0

In [36]:
# 1d
a = np.array([3])

In [41]:
a

array([3])

In [31]:
a.ndim

1

In [46]:
# 2d
b = np.array([[1,2,4],[3,5,4]])

In [47]:
b

array([[1, 2, 4],
       [3, 5, 4]])

In [48]:
b.ndim

2

In [55]:
# 3d

c =np.array([[[1,2,3,4],[7,8,5,9]]])

In [56]:
c

array([[[1, 2, 3, 4],
        [7, 8, 5, 9]]])

In [57]:
c.ndim

3

In [86]:
c2 = np.array([[[123,232,43],[987,532,755]],[[5,3,4],[7,2,9]]])

In [87]:
c2

array([[[123, 232,  43],
        [987, 532, 755]],

       [[  5,   3,   4],
        [  7,   2,   9]]])

In [88]:
c2.ndim

3

In [115]:
#Acesssing
# if 2d arrray then [row] [col]
# if 3d and more then [layer] [row] [col]   and [layer][slicing]

In [90]:
b.ndim

2

In [94]:
b[0][2]

4

In [100]:
c2.ndim

3

In [103]:
c2

array([[[123, 232,  43],
        [987, 532, 755]],

       [[  5,   3,   4],
        [  7,   2,   9]]])

In [105]:
c2[0][1][1]

532

In [108]:
# 4 9

c2[1][:,2]

array([4, 9])

In [109]:
# 987 532 755

c2[0][1,:]

array([987, 532, 755])

In [111]:
# 32
c2[1][:,1]

array([3, 2])

In [112]:
# 34
c2[1][0,1:]

array([3, 4])

In [118]:
#987, 532
c2[0][1,0:2]
c2[0][1,:2]

array([987, 532])

In [120]:
# 755
c2[0][1][2]

755

In [132]:
# 9
c2[1][1][2]

9

In [133]:
b

array([[1, 2, 4],
       [3, 5, 4]])

In [141]:
# reshape rule : it must not violating the multiplication   2*3=6
b.reshape(3,2)

array([[1, 2],
       [4, 3],
       [5, 4]])

In [139]:
b.reshape(1,6)

array([[1, 2, 4, 3, 5, 4]])

In [140]:
b.reshape(6,1)

array([[1],
       [2],
       [4],
       [3],
       [5],
       [4]])

In [145]:
#Matrix


np.zeros((3,3)).astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [146]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [149]:
np.ones((3,6),dtype='int32')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [152]:
np.full((2,7),8)

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [156]:
#arrange same like range


np.arange(5)

array([0, 1, 2, 3, 4])

In [157]:
np.arange(0,3)

array([0, 1, 2])

In [159]:
np.arange(1,9).reshape(4,2).astype('float16')

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]], dtype=float16)

In [161]:
#inbuilt random in numpy


np.random.rand(4)    # 0 TO 1

array([0.55299715, 0.21987189, 0.84683507, 0.2468608 ])

In [162]:
np.random.rand(90)

array([0.41861109, 0.99584876, 0.89355095, 0.72752568, 0.8293296 ,
       0.6358192 , 0.53428314, 0.80210236, 0.0986522 , 0.05601853,
       0.4515934 , 0.50173946, 0.25378479, 0.14980888, 0.17940744,
       0.44605953, 0.70123461, 0.47934844, 0.69352176, 0.68385479,
       0.39144286, 0.32085985, 0.83549653, 0.18383811, 0.48222234,
       0.02243731, 0.23967042, 0.88040961, 0.12358462, 0.80386587,
       0.41217749, 0.58934545, 0.81054293, 0.66188154, 0.78732516,
       0.52969621, 0.04574722, 0.14744682, 0.07158342, 0.17816218,
       0.73833702, 0.83097847, 0.33280744, 0.26737697, 0.23935052,
       0.68169426, 0.12456445, 0.00430109, 0.30647952, 0.64047994,
       0.9890569 , 0.30349473, 0.85454926, 0.29216967, 0.12168212,
       0.980074  , 0.12804585, 0.69757109, 0.52147654, 0.35247954,
       0.25300154, 0.3162616 , 0.91651643, 0.88718432, 0.88060151,
       0.94314085, 0.61027232, 0.48130352, 0.94013796, 0.32482634,
       0.32459489, 0.60769385, 0.19387036, 0.82069466, 0.27178

In [165]:
np.random.randint(4,750)

423

In [169]:
np.random.randint(4,750,size=10)

array([677, 394, 601, 598,  66, 665, 576,  76, 417, 663])

In [172]:
np.random.randint(3,90,23)     #23=how much

array([54, 82,  8, 12, 40, 52, 11, 51, 67, 43, 18, 79, 60, 84, 25, 64, 29,
       51, 82, 70, 65, 41, 71])

In [173]:
np.random.randn(5)    # randomly 5 number which show distribution data

array([-0.7273207 ,  0.31669236,  0.34825397, -0.48166533,  1.14192852])

In [180]:
np.random.randn(50)

array([-0.61374223, -0.30850139, -0.07621588, -0.97609744, -0.97998196,
       -0.29823521,  0.86428544, -0.27044718, -0.25959584, -0.76957003,
       -0.77428716,  0.77153158,  0.96570524,  1.2175858 ,  1.56133011,
        2.04196409,  0.78028933,  1.27723834, -0.57749566,  0.48082434,
       -1.30344092, -2.10919721, -0.48174189, -1.94751167, -0.24086976,
        0.84460168, -0.57773053, -1.28523314, -0.94655175,  0.89139423,
       -1.5639001 , -0.54247231,  1.11662033, -0.44011654,  1.27158995,
       -2.37465678, -0.68305276, -1.52964215,  1.09820347,  0.16183993,
        0.18583855, -0.92509678,  0.7608732 ,  0.01337031, -1.38240337,
       -0.10315714, -1.59177619,  1.02866027,  0.4497145 ,  2.04660735])